import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createLocalRunRecord, validateLocalRunRecord, writeLocalRunRecordAtomic, attributeGitEvidence } from "./local-run-ledger.mjs";
import { createTaskContract, runLocalWorkerTask } from "./local-worker-runtime.mjs";

const SHA = "0123456789abcdef0123456789abcdef01234567";
function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "devexec-observability-hardening-"));
  fs.writeFileSync(path.join(root, "README.md"), "fixture\n");
  execFileSync("git", ["-C", root, "init", "-q"]); execFileSync("git", ["-C", root, "config", "user.email", "test@example.invalid"]); execFileSync("git", ["-C", root, "config", "user.name", "DevExec"]); execFileSync("git", ["-C", root, "add", "README.md"]); execFileSync("git", ["-C", root, "commit", "-q", "-m", "fixture"]);
  const base = execFileSync("git", ["-C", root, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  return { root, task: createTaskContract({ task_id: "observability-hardening", repo: root, worktree: root, cwd: root, base_commit: base, goal: "bounded edit", allowed_paths: ["allowed.txt", "dirty.txt"], constraints: ["no commit"], test_command: [process.execPath, "-e", "process.exit(0)"], timeout: 30000, max_tool_calls: 2, output_limit: 2000 }) };
}
const passAdapter = (fn = async () => {}) => ({ identity: { runtime: "local", provider: "fake" }, async run(task) { await fn(task); return { status: "PASS", metrics: { wall_time_ms: 999999, first_tool: "https://bad.example/?token=x", prompt_tokens: 4 } }; } });

test("pre-dirty no-op cannot claim DONE", async () => { const f = fixture(); fs.writeFileSync(path.join(f.root, "dirty.txt"), "before\n"); const result = await runLocalWorkerTask(f.task, { adapter: passAdapter() }); assert.equal(result.result.status, "FAILED"); assert.deepEqual(result.result.changed_files, []); });
test("pre-dirty unchanged path is excluded while a new allowed edit is attributed", async () => { const f = fixture(); fs.writeFileSync(path.join(f.root, "dirty.txt"), "before\n"); const result = await runLocalWorkerTask(f.task, { adapter: passAdapter(async (task) => fs.writeFileSync(path.join(task.worktree, "allowed.txt"), "new\n")) }); assert.equal(result.result.status, "DONE"); assert.deepEqual(result.result.changed_files, ["allowed.txt"]); });
test("a pre-dirty path modified during the run is attributed", async () => { const f = fixture(); fs.writeFileSync(path.join(f.root, "dirty.txt"), "before\n"); const result = await runLocalWorkerTask(f.task, { adapter: passAdapter(async (task) => fs.writeFileSync(path.join(task.worktree, "dirty.txt"), "after\n")) }); assert.equal(result.result.status, "DONE"); assert.deepEqual(result.result.changed_files, ["dirty.txt"]); });
test("new or modified unexpected paths block even when provider says PASS", async () => { const f = fixture(); const result = await runLocalWorkerTask(f.task, { adapter: passAdapter(async (task) => fs.writeFileSync(path.join(task.worktree, "outside.txt"), "bad\n")) }); assert.equal(result.result.status, "BLOCKED"); assert.match(result.result.blocker, /unexpected changed paths/); });
test("attribution changes only on status or fingerprint mutation", () => { const before = { path_details: { "x.txt": { status: " M", fingerprint: SHA, fingerprint_bounded: true } } }; const same = { path_details: { "x.txt": { status: " M", fingerprint: SHA, fingerprint_bounded: true } } }; const changed = { path_details: { "x.txt": { status: " M", fingerprint: SHA.replace(/^0/, "1"), fingerprint_bounded: true } } }; assert.deepEqual(attributeGitEvidence(before, same).paths, []); assert.deepEqual(attributeGitEvidence(before, changed).paths, ["x.txt"]); });

test("ledger validation is recursively exact and fail-closed", () => { const record = createLocalRunRecord({ run_id: "safe-run", contract_fingerprint: SHA, base_commit: SHA }); validateLocalRunRecord(record); for (const mutate of [(r) => { r.harness.provider_usage.extra = 1; }, (r) => { r.selection.provider = "https://bad"; }, (r) => { r.base_commit = SHA.toUpperCase(); }, (r) => { r.outcome.tests = []; }]) { const copy = structuredClone(record); mutate(copy); assert.throws(() => validateLocalRunRecord(copy)); } });
test("model path is reduced to a safe basename and query is removed", () => { const record = createLocalRunRecord({ run_id: "safe-run", selection: { runtime: "local", provider: "freetoken", harness: "minimal-harness", model: "C:\\models\\qwen.gguf?token=secret#x" }, contract_fingerprint: SHA, base_commit: SHA }); assert.equal(record.selection.model, "qwen.gguf"); assert.doesNotMatch(record.selection.model, /https?:|token=|[\\/]/i); });
test("atomic writer is no-overwrite under same-run concurrency", async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "devexec-ledger-concurrency-")); const record = createLocalRunRecord({ run_id: "same-run", contract_fingerprint: SHA, base_commit: SHA }); const outcomes = await Promise.all(Array.from({ length: 20 }, () => Promise.resolve().then(() => { try { return writeLocalRunRecordAtomic(dir, record), "ok"; } catch { return "failed"; } }))); assert.equal(outcomes.filter((x) => x === "ok").length, 1); assert.deepEqual(fs.readdirSync(dir), ["same-run.json"]); });
test("parent wall metric is not overwritten by adapter metrics and first_tool is retained", async () => { const f = fixture(); const result = await runLocalWorkerTask(f.task, { adapter: passAdapter(async (task) => fs.writeFileSync(path.join(task.worktree, "allowed.txt"), "ok\n")), runLedgerDir: f.root }); assert.notEqual(result.result.runtime_metrics.wall_time_ms, 999999); const ledger = JSON.parse(fs.readFileSync(path.join(f.root, `${result.run_id}.json`), "utf8")); assert.notEqual(ledger.harness.parent_measured.wall_time_ms, 999999); assert.equal(ledger.harness.harness_reported.wall_time_ms, 999999); assert.equal(ledger.harness.harness_reported.first_tool, "https___bad.example__token_x"); });
